server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /openapi

amazon:
  aws:
    accesskey: @aws-key@
    secretkey: @aws-secret@
  dynamodb:
    region: @aws-region@
    endpoint: @aws-dynamo-endpoint@

multichannel:
    tableName: @table-name@
